
package Continuity::Mapper;

use strict;
use Coro::Cont;

sub new {
  my $this = shift;
  my $class = ref($this) || $this;
  my $self = {};
  $self = {%$self, @_};
  bless $self, $class;
  return $self;
}

sub debug {
  my ($self, $level, $msg) = @_;
  if($level >= $self->{debug}) {
   print STDERR "$msg\n";
  }
}

# Sessions are currently generated by starting with zero and going up from
# there... not a very good way!
my $sessionIdCounter;

sub getSession {
  my ($self, $request) = @_;
  #print "Headers: " . $request->as_string();

  my $cookieHeader = $request->header('Cookie');
  $self->debug(3, "Cookies: $cookieHeader");
  
  $self->debug(3, "sessionIdCounter: $sessionIdCounter");
  if($cookieHeader =~ /sessionid=(\d+)/) {
    $self->debug(3, "Found sessionId!");
    return $1;
  }
  return $sessionIdCounter++;
}

sub map {
  my ($self, $request, $conn) = @_;
  my $c;
  my $sessionId = $self->getSession($request);
  if(defined $self->{continuations}{$sessionId}) {
    $c = $self->{continuations}{$sessionId};
  } else {
    # In this case, lets create a new continuation
    $c = $self->{mkNewCont}->($request);
    # And we call it one time to let it do some initialization
    $c->($self);
    # And we stash it away!
    $self->{continuations}{$sessionId} = $c;
  }

  # And send our session cookie
  # Perhaps instead we should be adding this to a list of headers to be sent
  print $conn "Set-Cookie: sessionid=$sessionId\r\n";
  return $c;
}

sub set_cont_maker_sub {
  my ($self, $sub) = @_;
  $self->{mkNewCont} = $self->mkContMaker($sub);
}

# Take a sub ref and give back a continuation. Just a shortcut
sub mkcont {
  my ($self, $func) = @_;
  my $cont = csub { $func->(@_) };
  return $cont;
}

sub mkContMaker {
  my ($self, $sub) = @_;
  my $mkNewCont = sub {
    $self->mkcont($sub)
  };
  return $mkNewCont;
}

1;

